import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: ["./src/app/**/*.{ts,tsx}", "./src/components/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        "border-strong": "hsl(var(--border-strong))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        brand: {
          DEFAULT: "hsl(var(--brand))",
          dim: "hsl(var(--brand-dim))",
          bright: "hsl(var(--brand-bright))",
        },
        grey: {
          50: "rgb(var(--grey-50))",
          100: "rgb(var(--grey-100))",
          200: "rgb(var(--grey-200))",
          300: "rgb(var(--grey-300))",
          400: "rgb(var(--grey-400))",
          500: "rgb(var(--grey-500))",
          600: "rgb(var(--grey-600))",
          700: "rgb(var(--grey-700))",
          800: "rgb(var(--grey-800))",
          900: "rgb(var(--grey-900))",
        },
        "brand-purple": {
          50: "rgb(var(--brand-purple-50))",
          100: "rgb(var(--brand-purple-100))",
          200: "rgb(var(--brand-purple-200))",
          300: "rgb(var(--brand-purple-300))",
          400: "rgb(var(--brand-purple-400))",
          500: "rgb(var(--brand-purple-500))",
          600: "rgb(var(--brand-purple-600))",
          700: "rgb(var(--brand-purple-700))",
          800: "rgb(var(--brand-purple-800))",
          900: "rgb(var(--brand-purple-900))",
        },
        "brand-blue": {
          50: "rgb(var(--brand-blue-50))",
          100: "rgb(var(--brand-blue-100))",
          200: "rgb(var(--brand-blue-200))",
          300: "rgb(var(--brand-blue-300))",
          400: "rgb(var(--brand-blue-400))",
          500: "rgb(var(--brand-blue-500))",
          600: "rgb(var(--brand-blue-600))",
          700: "rgb(var(--brand-blue-700))",
          800: "rgb(var(--brand-blue-800))",
          900: "rgb(var(--brand-blue-900))",
        },
        blue: {
          50: "rgb(var(--blue-50))",
          100: "rgb(var(--blue-100))",
          200: "rgb(var(--blue-200))",
          300: "rgb(var(--blue-300))",
          400: "rgb(var(--blue-400))",
          500: "rgb(var(--blue-500))",
          600: "rgb(var(--blue-600))",
          700: "rgb(var(--blue-700))",
          800: "rgb(var(--blue-800))",
          900: "rgb(var(--blue-900))",
        },
        success: "hsl(var(--success))",
        warning: "hsl(var(--warning))",
        danger: "hsl(var(--danger))",
        info: "hsl(var(--info))",
        "surface-0": "hsl(var(--surface-0))",
        "surface-1": "hsl(var(--surface-1))",
        "surface-2": "hsl(var(--surface-2))",
        "surface-3": "hsl(var(--surface-3))",
        "surface-4": "hsl(var(--surface-4))",
        "surface-card": "hsl(var(--surface-card))",
        "surface-control": "hsl(var(--surface-control))",
        "surface-control-hover": "hsl(var(--surface-control-hover))",
        "tier-starter": "hsl(var(--tier-starter))",
        "tier-partner": "hsl(var(--tier-partner))",
        "tier-elite": "hsl(var(--tier-elite))",
        "tier-legend": "hsl(var(--tier-legend))",
        "group-gold": "hsl(var(--group-gold))",
        "group-silver": "hsl(var(--group-silver))",
        "group-bronze": "hsl(var(--group-bronze))",
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        card: "14px",
        control: "8px",
      },
      boxShadow: {
        "brand-glow": "0 0 16px hsl(var(--brand-glow))",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;
